# .circleci/config.yml
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: npm start

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
